### ISSUE TITLE
[Feature] DB 설계

### ISSUE THREAD

**Issue by minkukjo** [Coding-Hogwarts/sns#1]
## 개발 내용

- Dbschema를 활용해 테이블 설계

**Comment by hyerin6** [comment]
![20210801](https://user-images.githubusercontent.com/33855307/127762146-487b6e0a-86d5-485f-a8eb-8a45d64fc718.png)

**Comment by minkukjo** [comment]
@hyerin6 
안녕하세요 혜린님, 역시 디프만 넥스터즈 짬밥(?)이 있어서 그런지 알아서 잘 DBSchema로 구성 잘 해주셨네요~
아주 잘하셨어요.

아래는 피드백 내용입니다~

## 피드백
- like 테이블의 id는 어떤 용도인가요? PK로써 조회할 일이 없을 듯 한데, user_id와 post_id를 복합키로 하고 PK로 구성해보면 어떨까요??
- follow 테이블도 같은 이유로 id로는 조회할 일이 별로 없을 듯 합니다. follower_id와 following_id를 PK로 해보면 어떨까요?
- image 테이블에 post_id 컬럼에 index를 걸어주는 센스 좋았습니다~
- 혹시 설계하신 SNS에 댓글 기능은 없는건가요? (요거는 피드백이라기 보단 질문입니다 ㅎㅎ)
- post의 user_id가 unique key인 이유는 무엇인가요?? 저렇게 설정하면 한명의 유저는 하나의 게시글만 작성할 수 있을 것 같아서요~ 의도하신거라면 죄송합니다~ ㅎㅎ

**Comment by hyerin6** [comment]
<img width="912" alt="스크린샷 2021-08-03 오전 1 10 12" src="https://user-images.githubusercontent.com/33855307/127892816-c64c09a3-412c-4ba1-9c08-74818291dfa2.png">

* 복합키로 다시 설계해봤는데 fk도 그대로 유지하는게 맞는지....(?)
mysql 기본키 부분을 찾아봤는데 헷갈려서 우선 이렇게 설계해봤습니다.      
* 댓글은 대댓글 기능도 있다고 가정하고 parent를 추가해봤습니다. 
* user_id는 추가할 때 박스에 체크를 잘못했나봐요! 다시 수정했습니다~

**Comment by minkukjo** [comment]
@hyerin6 
넵넵 보통 회사에선 FK를 잘 안쓰긴 하는데요~ ( 물론 JPA의 연관관계를 쓰려면 불가피하긴 합니다만... )
그 이유는 DBA들이 외래키 생성을 하게 되면 DB 성능이 저하되고 DDL 작업에 대한 제약도 있다보니 FK 사용을 좋아하지않습니다.

저희는 토이니까 FK를 쓰도록 합시다. 가급적이면 cascade 옵션도 걸어주세요~ 거는 방법은 아래 이미지로 첨부드렸습니당
<img width="408" alt="스크린샷 2021-08-03 오전 11 18 06" src="https://user-images.githubusercontent.com/43809168/127947203-2182f9c8-7238-47e7-a8d1-8595d0a6ba9f.png">

- 복합키 설정을 잘하셨어요 FK도 그대로 유지하도록 합시다~
- 대댓글 기능까지 설계하신 부분 좋네요~
- 기능 개발할 때는 댓글부터 개발하고 대댓글 기능을 개발하도록 순차적으로 진행해봅시다!
- DB 설계는 이정도면 충분할 듯 합니다. 추후에 필요하면 계속해서 컬럼을 추가-삭제하는 방식으로 진행합시다. 개발 진행해봐요~

**Comment by minkukjo** [comment]
<img width="853" alt="스크린샷 2021-08-03 오전 11 28 38" src="https://user-images.githubusercontent.com/43809168/127948136-b7a93e24-485e-4616-95c1-41b51a04c729.png">
<img width="760" alt="스크린샷 2021-08-03 오전 11 28 45" src="https://user-images.githubusercontent.com/43809168/127948145-589e5bff-8f6b-4369-ba7a-d0a80a6861ae.png">

**Comment by minkukjo** [comment]
@hyerin6 
이번주에는 JPA의 연관관계 매핑을 사용할지 말지, QueryDSL의 사용 등에 대해서 논의를 해볼게요~
우선은 Entity, Request/Response 모델, 서비스, 컨트롤러, 테스트 코드 개발 진행해주시면 되겠습니당 (시간이 모자라시면 가능한 부분만요~)
